export enum StickerType {
  SHINING="SHINING",
  HEART="HEART",
  GIFTBOX="GIFTBOX",
  CAKE="CAKE",
  COFFEE="COFFEE",
  CAMERA="CAMERA",
  LIGHT_STICK="LIGHT_STICK",
  TICKET="TICKET",
  MUSICAL_NOTE="MUSICAL_NOTE",
  MONEY="MONEY",
  DISPLAY_BOARD="DISPLAY_BOARD",
  BASEBALL="BASEBALL",
}